version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: curso_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
